
logging:
  level:
    io.github.resilience4j.circuitbreaker: INFO
    ru.yandex.practicum.client: DEBUG
    ru.yandex.practicum.service: DEBUG

management:
  endpoints.web.exposure.include: health,metrics

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:postgresql://localhost:5432/shtech?currentSchema=cart
    username: shtech
    password: verysecretword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 0
  shutdown: graceful

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - feign.FeignException.FeignClientException
